ENV_STRATEGY = ["impulsive", "demanding", "cautious", "randomer"]
ENV_QUANTITY_OF_PROPERTIES = 20
ENV_NUMBER_SIMULATION = 300
ENV_TIMEOUT_ROUND = 1000
ENV_PLAYER_MONEY = 300.0
ENV_PLAYER_MONEY_ROUND = 100.0
